server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: zertallian
    password: password
    url: jdbc:postgresql://localhost:5432/customerDB
    driver-class-name: org.postgresql.Driver

topic:
  name: t.client.action