server:
  port: 8081
spring:
  application:
    name: customer-service
  datasource:
    username: zertallian
    password: password
    url: jdbc:postgresql://localhost:5432/customerDB
    driver-class-name: org.postgresql.Driver

topic:
  name: t.client.action

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/