version: "3.7"

networks:
  kafka-net:
    name: kafka-net
    driver: bridge


services:

  api-gateway:
    build:
      context: /api-gateway
      dockerfile: Dockerfile
    container_name: 'api-gateway-service'
    ports:
      - 8080:8080

  autorisation:
    build:
      context: /authorisation
      dockerfile: Dockerfile
    container_name: 'autorisation-service'

  customer:
    build:
      context: /customer
      dockerfile: Dockerfile
    container_name: 'customer-service'

  eureka-server:
    build:
      context: /eureka-server
      dockerfile: Dockerfile
    container_name: 'eureka-server-service'

  mail:
    build:
      context: /mail
      dockerfile: Dockerfile
    container_name: 'mail-service'

  orders:
    build:
      context: /orders
      dockerfile: Dockerfile
    container_name: 'orders-service'

  products:
    build:
      context: /products
      dockerfile: Dockerfile
    container_name: 'products-service'


  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    restart: "no"
    networks:
      - kafka-net
    ports:
      - "2181:2181"

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: "no"
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    networks:
      - kafka-net
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"

  rabbitMQ:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672