server:
  port: 8082
spring:
  application:
    name: customer
  datasource:
    username: zertallian
    password: password
    url: jdbc:postgresql://localhost:5433/orderDB
    driver-class-name: org.postgresql.Driver